
spring.datasource.url=jdbc:mysql://localhost:3306/andiamo?useUnicode=true&characterEncoding=UTF-8

spring.datasource.username=root
spring.datasource.password=BEDOUI123

spring.jpa.hibernate.ddl-auto=update

server.port=8083
server.address=0.0.0.0


jwt.secret=f4d37596c70fea5b208ec0ecc6c78816c33ed874